"""Does the shape of the curve tell you anything about the stock market?

Produces every figure in the "The stock market: nothing" section of
notes/methods.md. Written after noticing those numbers were quoted in the note
but generated by no committed script -- the same failure a reviewer caught
elsewhere.
"""
import sys, os, math, statistics
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from econlib import *
from dat import load
import json

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
man, LAB, rows = load()
D = man["dates"]; n = man["dayCount"]
sp = json.load(open(os.path.join(root, "docs/data/context.json")))["series"]["SP500"]["values"]

import struct
SC = man["scale"]; OF = man["offset"]; N = len(LAB)
arr = struct.unpack_from("<%dH" % (n*(N+1)), open(os.path.join(root, "docs/data/tenors.bin"), "rb").read())
st = N+1
v = lambda d, t: arr[d*st+t]/SC-OF
i2, i10 = LAB.index("2 Yr"), LAB.index("10 Yr")

def fwd(i, days):
    j = min(i+days, n-1)
    while j > i and sp[j] is None: j -= 1
    if sp[i] is None or sp[j] is None: return None
    return 100*(sp[j]/sp[i]-1)

print("=" * 72)
print("DOES THE CURVE PREDICT THE STOCK MARKET?")
print(f"S&P coverage: {D[0]} to {D[n-1]}\n")

# 1. correlation of slope with forward returns
for h, lab in ((252, "12 months"), (504, "24 months")):
    pairs = [(v(i, i10)-v(i, i2), fwd(i, h)) for i in range(n-h) if fwd(i, h) is not None]
    xs = [p[0] for p in pairs]; ys = [p[1] for p in pairs]
    mx, my = statistics.mean(xs), statistics.mean(ys)
    num = sum((a-mx)*(b-my) for a, b in pairs)
    den = (sum((a-mx)**2 for a in xs)*sum((b-my)**2 for b in ys))**0.5
    r = num/den
    print(f"  slope (10yr-2yr) vs S&P forward {lab}:  r = {r:+.3f}   "
          f"r^2 = {r*r:.3f}  ({100*r*r:.1f}% of the variation)   n = {len(pairs)} days")

# 2. unconditional baseline
print()
for h, lab in ((252, "12m"), (504, "24m")):
    xs = sorted(fwd(i, h) for i in range(n-h) if fwd(i, h) is not None)
    print(f"  BASELINE {lab}: mean {sum(xs)/len(xs):+.1f}%   median {xs[len(xs)//2]:+.1f}%   "
          f"negative on {100*sum(1 for x in xs if x < 0)/len(xs):.0f}% of days")

# 3. what happened after each inversion began
print("\n  S&P after each 2s10s inversion onset (60+ clean days before it):")
onsets = []; clean = 0
for i in range(n):
    if v(i, i10) < v(i, i2):
        if clean >= 60: onsets.append(i)
        clean = 0
    else: clean += 1
print(f"  {'onset':<12}{'+12m':>9}{'+24m':>9}")
tot12 = []
for i in onsets:
    a, b = fwd(i, 252), fwd(i, 504)
    if a is not None: tot12.append(a)
    print(f"  {D[i]:<12}{(f'{a:+.1f}%' if a is not None else 'n/a'):>9}"
          f"{(f'{b:+.1f}%' if b is not None else 'n/a'):>9}")
print(f"  {'MEAN':<12}{sum(tot12)/len(tot12):>+8.1f}%")
print(f"\n  Compare the baseline above. n = {len(onsets)} episodes -- far too few to")
print("  be a test in its own right; it is shown because people quote it.")
